### ISSUE TITLE
Invalid URLs in provenance

### ISSUE THREAD

**Issue by MarkLodato** [hi-artem/provenance-generator-buildkite-plugin#3]
From [examples/provenance.json](https://github.com/hi-artem/provenance-generator-buildkite-plugin/blob/main/examples/provenance.json):

- `builder.id` is not a valid URL - missing `https://` prefix
- `materials.url` is not a valid URL. For GitHub I recommend using `git+https://github.com/virtru/devhacks` (`git+https://` scheme, no `.git` suffix)

**Comment by hi-artem** [comment]
These issues should be addressed in the latest plugin release! 

Thanks @MarkLodato
